### ISSUE TITLE
Suggestion: Allow Ability to Hide Menubar

### ISSUE THREAD

**Issue by rehatkathuria** [r-thomson/Nightfall#10]
Thank you for this lovely utility, the ability to animate the toggle is lovely. One thing I'd love to be able to do is to toggle the menubar icon to be hidden––is this something that's been considered?

**Comment by r-thomson** [comment]
This is a nice suggestion, but currently the menu bar icon is the only way to interact with the app. Unless that changes, there would be no way to re-show the menu bar icon if it were hidden.

**Comment by r-thomson** [comment]
One possible implementation of this could be that the app would re-show itself in the menu bar whenever [`applicationShouldHandleReopen`](https://developer.apple.com/documentation/appkit/nsapplicationdelegate/1428638-applicationshouldhandlereopen) is called. There'd definitely need to be some additional UX to make it clear enough to the user, but I think it's probably feasible.

**Comment by r-thomson** [comment]
Added in https://github.com/r-thomson/Nightfall/commit/00610ed5b287bc4d4bbe6b5c9d7940e0c17d10a9, will be included in next release.
