### ISSUE TITLE
Suggestion: Native Apple Silicon Support

### ISSUE THREAD

**Issue by evanbrierton** [r-thomson/Nightfall#11]
Hi I just started using this app on the M1 MacBook Pro and it runs fine via Rosetta but if possible a native release would be nice. It should only involve updating the architecture list and rebuilding as detailed [here](https://developer.apple.com/documentation/apple-silicon/building-a-universal-macos-binary).

Another related suggestion which I can create another issue for if needed is updating the app icon to be consistent with the new icon style introduced in Big Sur.

Thanks for reading!

**Comment by r-thomson** [comment]
Thanks for the suggestion, I will release an update as a universal binary when I have the time.

I’m not currently running Big Sur on my Macs, so I wouldn’t be able to test how well a new app icon appears alongside the other Big Sur icons. Saving this change for the future for now.

**Comment by evanbrierton** [comment]
The templates for the app icon are available [here](https://developer.apple.com/design/resources/#macos-apps) if you are interested.

Thanks for the consideration, really great app!

**Comment by Chunkybearhaha** [comment]
Kinda new to this, but...how do I install this on my Mac? I have downloaded Github desktop client. Thanks!!

**Comment by r-thomson** [comment]
@Chunkybearhaha You do not need to install the GitHub client to install this app. All you need to do is click on "Nightfall.dmg"  on the [latest release](https://github.com/r-thomson/Nightfall/releases/latest).

In the future, please avoid replying to an existing issue with content not related to the original issue.
