### ISSUE TITLE
[[ Suggestion ]] Add ability to check for updates

### ISSUE THREAD

**Issue by SwiftArtery** [r-thomson/Nightfall#16]
Firstly, thank you for this tool! I use it a lot to test appearance stuff when developing.

I didn't realise I was on an older version (2.1.1) for a while as I installed this ~1 year ago and hadn't bothered checking for updates.

I think it could be quite useful to have either automatic update checks (say, weekly), or maybe a "Check for Updates" option in the right-click menu.

**Comment by r-thomson** [comment]
This is already implemented— Preferences → Check for new versions.

When there's a new update available, you should see "Update..." in the dropdown menu.
