### ISSUE TITLE
Apple marks Nightfall as malware

### ISSUE THREAD

**Issue by hvwees** [r-thomson/Nightfall#17]
A few days ago MacOS reported that nightfall will damage your computer.

<img width="336" alt="Screenshot 2021-12-16 at 16 10 45" src="https://user-images.githubusercontent.com/7431769/146397227-0869809e-e2d1-4cfd-bfb4-5632f8b7eb5d.png">

**Comment by r-thomson** [comment]
Could you run this command please?
```
codesign -vvv /Applications/Nightfall.app/
```

**Comment by hvwees** [comment]
```
~ % codesign -vvv /Applications/Nightfall.app/

--prepared:/Applications/Nightfall.app/Contents/Library/LoginItems/NightfallLauncher.app
--validated:/Applications/Nightfall.app/Contents/Library/LoginItems/NightfallLauncher.app
/Applications/Nightfall.app/: valid on disk
/Applications/Nightfall.app/: satisfies its Designated Requirement
```

**Comment by r-thomson** [comment]
Interesting, `codesign` seems to be showing that the app's signature is fine.

If anyone can hunt down the cause of this, please let me know.

**Comment by hvwees** [comment]
Not sure which version I use the have, but after a "brew upgrade" MacOS no longer report this as malware.
Now I have version 2.1.3 

Still weird that the older version was reported as malware, but it seems to be fixed now.
