### ISSUE TITLE
Smooth transition not visible in latest master

### ISSUE THREAD

**Issue by etrahretep** [r-thomson/Nightfall#19]
When building latest master changing smooth transition values is not possible. There not shown, although screen recording is permitted.
Xcode 13.2.1 Macos 12.2 (21D48)

<img width="245" alt="Schermafbeelding 2022-01-23 om 15 15 12" src="https://user-images.githubusercontent.com/42773309/150682760-7c51a8b8-a5e0-4bef-a0cb-e6e72750439b.png">
.

**Comment by r-thomson** [comment]
Is the transition itself not working, or is it just adjusting the timing values?

**Comment by etrahretep** [comment]
It doesn't seem to remember the old values (0,3/3). There is a very little delay compared to Smooth transitions unchecked.
Adjusting timing is not possible for there's nothing to adjust...

**Comment by r-thomson** [comment]
The version on master is using a private system API for the transition. This API uses the minimum possible delay based on how long it takes all the apps to switch over, but the timing values can't be adjusted.

**Comment by etrahretep** [comment]
Ah, oke that's why. Pity, for I liked the looong transition.
