### ISSUE TITLE
Record this computers' screen

### ISSUE THREAD

**Issue by mijndert** [r-thomson/Nightfall#2]
While toggling to dark/light mode for the first time, a prompt comes up asking the user to grant Nightfall permission to record the screen.
I consider this a bug.

**Comment by r-thomson** [comment]
The prompt appears because the fade effect is done by capturing an image of the screen using `CGDisplayCreateImage`. Without screen recording permissions, the effect can't be accomplished.

**Comment by synchronizing** [comment]
This info would be relevant in the README, I believe, with link to the relevant piece of code for this. Sketched me out for a second after `brew install`'ing and came straight to the repo to see what was going on. 

Great utility @r-thomson nonetheless. I use to use Automator for this, but Nightfall does the same job 10x better. Thank you!

**Comment by r-thomson** [comment]
@synchronizing Thank you for the suggestion, I’ve added it to the project’s README
