### ISSUE TITLE
Mac Malware detection: "Nightfall.app" will damage your computer

### ISSUE THREAD

**Issue by kisfairmed** [r-thomson/Nightfall#21]
Hey,

today I restarted my MacBook to install a minor Update (OSX 11.6.3) and got this message: 
> “Nightfall.app” will damage your computer. You should move it to the Trash.

I installed the nightfall (V 2.1.2) via brew. I'm pretty sure it's a false positive.

<img width="367" alt="image" src="https://user-images.githubusercontent.com/83448788/153141599-e9abf126-484b-4e25-9aa6-e3d442078a76.png">

**Comment by r-thomson** [comment]
Please update to the latest version and try again.

**Comment by kisfairmed** [comment]
I installed V 3.0.0 and got no more message.Seems to work
