### ISSUE TITLE
Pick Dark/Light mode based on light sensor

### ISSUE THREAD

**Issue by ghosalmartin** [r-thomson/Nightfall#23]
To really crank up the laziness of devs have the modes be determined by the ambient light.

From a quick Google I found

https://stackoverflow.com/questions/17625495/how-do-you-programmatically-access-the-ambient-light-sensor-on-mac-os-x-10-5

But thanks to Apple that may or may not work.

**Comment by r-thomson** [comment]
Interesting idea, but I'm not sure if the implementation could be practical enough that people would actually want to use it.

* Depending on how good the sensor data is, I could see dark mode flipping on and off annoyingly based on fluctuations in light level
* I could see things getting pretty weird if this feature tries to interact with the system preference to activate dark mode at sundown

**Comment by janwilmake** [comment]
I would love to try this out. I'm working outside a lot. I think there's enough sensor information to see that it's quite bright out here... You could also set a threshold, like, it has to be very bright for more than a minute, before it switches to light mode.

Anyway, a shortcut is already great, but I think this would be a good addition!

**Comment by JesusAndradeAval** [comment]
It will be activate in a percentage range (customizable) of darkness

**Comment by r-thomson** [comment]
Closed as not planned
