### ISSUE TITLE
"Nightfall.app" can't be opened because Apple cannot check it for malicious sofware

### ISSUE THREAD

**Issue by keithly** [r-thomson/Nightfall#24]
Attempting to launch Nightfall 3.0.0 on macOS 12.4 for the first time:

<img width="262" alt="Screen Shot 2022-05-25 at 7 58 42 PM" src="https://user-images.githubusercontent.com/940663/170393597-5daaceea-e2c8-4ea2-8b4d-4056908ecd84.png">

**Comment by r-thomson** [comment]
[See the Readme](https://github.com/r-thomson/Nightfall#installation)

> Note: these builds are not signed with a developer ID; you will need to bypass Gatekeeper to run Nightfall. See [Apple Support: Open a Mac app from an unidentified developer](https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/mac) for instructions.
