### ISSUE TITLE
Smooth Transition doesn't work on the wallpaper & menu bar when switching from dark to light.

### ISSUE THREAD

**Issue by alanmicah** [r-thomson/Nightfall#25]
Currently running:
- macOS Monterey 12.5.1
- Nightfall Version 2.1.3 (145853c)

My current Nightfall smooth transition preferences are:
- Delay: 0 seconds
- Duration: 0.5 seconds

I have included a screen capture.

The smooth transition works very nicely when in Light mode and transitioning to dark mode. However, when transitioning from dark mode to light mode there is no smooth transition for the menu bar and wallpaper. When transitioning from dark to light mode there is a delay of fewer than 1 second before the system changes to light mode and there is no smooth transition it's just a slightly delayed, sudden appearance change. The application windows still have a smooth transition e.g. the Finder window, Safari, Chrome etc.

From Dark to Light mode I noticed that if I increased the smooth transition duration there would still be a delay and the menu bar&wallpaper still "jolt" a little before the transition started, however, the smooth transition would be visible.
Conversely, if I turned off Smooth transition there would still be a delay when transitioning from Dark to Light mode.

https://user-images.githubusercontent.com/31675641/185997834-d3b08d95-456b-44be-a3f8-0d92336697c1.mov

**Comment by r-thomson** [comment]
Thank you for this very detailed and well-formatted report.

This is just the OS taking some time to switch appearances. Try bumping up the transition delay to hide the effect.

Since v3.0 Nightfall uses a private system API to change between light and dark mode. This should, in theory, wait until the system UI elements have finished updating, but it's really out of the app's hands at that point.

**Comment by alanmicah** [comment]
No worries.

Ahh I see ok. I tried your suggestion and found that a delay of 0.5 seconds hides the system effect, making the smooth transition visible from dark to light mode. Thank you!
