### ISSUE TITLE
Visual Finder bug when switching to light mode

### ISSUE THREAD

**Issue by christian-mall** [r-thomson/Nightfall#3]
Hi,

I really like your app, it's very handy for me. But I just encountered a bug in Finder. Here's what happened:

- Switched to dark mode
- Turned off MacBook Pro
- Turned it on
- Then when I went into the finder some of my folders still had the dark mode look (see here: https://www.dropbox.com/s/wimxfa1l4udnpbb/Bildschirmfoto%202020-03-04%20um%2011.28.15.png?dl=0)
- A MacBook restart fixed this

Maybe you could have a look into this issue. That would be awesome :-)

p.s. Just a small feature suggestion: I would find it so great if you implemented an option to always launch in light mode.

**Comment by christian-mall** [comment]
Update: I just noticed that when switching to dark mode (even using macOS' switch) the buggy folders actually stay in LIGHT mode. Maybe there's a macOS bug going on ;-)

**Comment by r-thomson** [comment]
This does appear to be a bug with macOS, not Nightfall.
