### ISSUE TITLE
App asks for recording permissions when it already has it

### ISSUE THREAD

**Issue by rainx1e** [r-thomson/Nightfall#31]
As the title says, I turn on the animation, it asks for recording permission, I give it permission and restart it, and then it still asks for permission and the animation doesn't work. I've tried restarting and still doesn't work. I installed with homebrew.

<img width="1440" alt="Screenshot to show this" src="https://github.com/r-thomson/Nightfall/assets/68461099/661a956a-52d0-449b-9836-b542e129703a">

**Comment by r-thomson** [comment]
I have experienced this in macOS Sonoma myself on multiple apps; I think it's an OS bug.

Try removing Nightfall from that list first and let me know if that works.

**Comment by rainx1e** [comment]
> I have experienced this in macOS Sonoma myself on multiple apps; I think it's an OS bug.
> 
> Try removing Nightfall from that list first and let me know if that works.

That fixed it. Thanks!
