### ISSUE TITLE
Permissions error

### ISSUE THREAD

**Issue by timwendel** [r-thomson/Nightfall#32]
Hey there.
First off, thank you for making this awesome little app, 2nd - is there a way to donate, like www.buymeacoffee.com or so?

And last but not least (I know it's a bit of a legacy thing as my work mac is still Monterey), I'm getting a funny error regarding screen recording permissions. I've already granted this permission but I still get a popup asking to grant access. Nothing wild but I thought I mention it.

Thanks again for this great little tool.
btw: It runs perfectly on my private M2 :)

<img width="1273" alt="Screenshot 2023-12-14 at 13 19 17" src="https://github.com/r-thomson/Nightfall/assets/2961734/4b8a6948-fa55-4c1b-895d-ee257d1c4d46">
<img width="612" alt="Screenshot 2023-12-14 at 13 19 31" src="https://github.com/r-thomson/Nightfall/assets/2961734/5a1d9b58-61a6-4b17-8ef3-116c449e6de3">

**Comment by r-thomson** [comment]
Please take a look at #31 and let me know if that resolves the issue for you.
