### ISSUE TITLE
Regularly crashing?

### ISSUE THREAD

**Issue by iandoesallthethings** [r-thomson/Nightfall#34]
I've noticed that whenever I resume from the laptop being closed or asleep, I have to reopen nightfall. I'm not sure if it's crashing or closing itself, but it adds a fair bit of friction.

I'm on an M1 Max running Sonoma 14.5.

**Comment by r-thomson** [comment]
I run Nightfall on all of my Macs and haven't noticed any crashing, can you check if there are any crash logs? Console.app → Crash Reports

**Comment by r-thomson** [comment]
Closing: can not reproduce
