### ISSUE TITLE
why does nightfall request screen recording capabilities?

### ISSUE THREAD

**Issue by rbedger** [r-thomson/Nightfall#36]
I am probably just ignorant of how Mac permissions work, but I'm curious what it is that requires the request for screen recording capabilities. I denied it and the application works just fine.

**Comment by ivan** [comment]
It's mentioned in https://github.com/r-thomson/Nightfall?tab=readme-ov-file#using-animated-transitions

**Comment by r-thomson** [comment]
Nightfall uses a [private system API](https://github.com/r-thomson/Nightfall/blob/9e3f0a1f63d7906c05a3b5f348296be89b997c40/Nightfall/BridgingHeader.h) to accomplish the smooth fade between light and dark modes. The way that API works internally is that it takes a screenshot and overlays that while the theme change is happening.

You can use Nightfall without screen recording permission, but the smooth transition won’t work.

**Comment by rbedger** [comment]
got it, thanks!  and my apologies i did not see this question answered in the README before i posted.
