### ISSUE TITLE
incorrect file path. 

### ISSUE THREAD

**Issue by aslanyanhaik** [r-thomson/Nightfall#5]
error: Build input file cannot be found: '/Users/ryanthomson/Developer/Nightfall/Nightfall/Views/PreferencesView.swift'

Please replace 
`AFCF6CB223B5254400C5CA70 /* PreferencesView.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; name = PreferencesView.swift; path = /Users/ryanthomson/Developer/Nightfall/Nightfall/Views/PreferencesView.swift; sourceTree = "<absolute>"; };`

with

`AFCF6CB223B5254400C5CA70 /* PreferencesView.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = PreferencesView.swift; sourceTree = "<group>"; };`

in project.pbxproj file

**Comment by r-thomson** [comment]
Fixed in 7374ef6

Thanks for reporting this, I have no idea how that one file ended up with an absolute path.
