### ISSUE TITLE
AppleScript error on launch

### ISSUE THREAD

**Issue by mibzman** [r-thomson/Nightfall#6]
When I launch nightfall I get a dialog box that says `An AppleScript error occurred. Error -2147450879`. I've accepted everything in system preferences.

[This]( https://macscripter.net/viewtopic.php?id=44686) indicates the full error message is `cannot set default target of scripting component 0 to (null)`

**Comment by r-thomson** [comment]
To clarify, does this error occur at startup or when you try to toggle dark mode?

**Comment by mibzman** [comment]
The error happens when I toggle dark mode.  Sorry!

**Comment by r-thomson** [comment]
As of https://github.com/r-thomson/Nightfall/commit/6577a93a6397aa2796c5c8a7240f032ab9039e83, AppleScript is no longer used
