### ISSUE TITLE
Menu bar item frequently gets stuck in opposite setting

### ISSUE THREAD

**Issue by rickydameliocroc** [r-thomson/Nightfall#7]
<img width="117" alt="Screen Shot 2020-09-15 at 17 53 20" src="https://user-images.githubusercontent.com/49666675/93181848-59092b80-f77c-11ea-96eb-24e280c8cdeb.png">

macOS 10.15.6 (19G2021)

**Comment by r-thomson** [comment]
Can you provide a way to consistently reproduce this issue?

**Comment by rickydameliocroc** [comment]
Unfortunately I haven't found any pattern, it seems very random. Maybe 50% of the time.

If it helps, my settings are:
Smooth transition:
- Delay: 0
- Duration: 0.6

**Comment by r-thomson** [comment]
Cannot reproduce
